### ISSUE TITLE
Printing does not re-write previous progress bar

### ISSUE THREAD

**Issue by freckletonj** [weavejester/progrock#1]
Also, if my code tries to print something, it's hopelessly jumbled within the multiple lines of the progress bar. (in the pic, you may notice `EXAMPLE ENDPOINT: MOCK: ...`)

I tracked this down from my use of `duct` and I'm using it within emacs/cider/nrepl.

PS, i love everything about `duct` and the slew of awesome libs you make, weavejester!

![image](https://cloud.githubusercontent.com/assets/8399149/19779120/e4179ba2-9c3c-11e6-9cd7-c9479cdfaf52.png)

**Comment by weavejester** [comment]
I believe this is an issue with CIDER/nREPL rather than Progrock. In a real terminal the code behaves correctly, but CIDER doesn't seem to support the `\r` character.

Is there any reason you're not using CIDER's own test runner? As its integrated into Emacs, that would be the better choice anyway.
