### ISSUE TITLE
How to set ETA?

### ISSUE THREAD

**Issue by p1mps** [weavejester/progrock#3]
I can't find it in the documentation. How can I set/calculate the ETA?
Btw, nice library! good job :)

**Comment by weavejester** [comment]
Progrock estimates the ETA from the current progress and elapsed time. So if at 1 minute it's done 25%, then it estimates the remaining time to be 3 minutes.

If you want a different remaining time, you can always add one yourself to the text string being generated. I'd also welcome a PR that adds an option to `render` that supplies a function for calculating the remaining time.

**Comment by p1mps** [comment]
I was asking because I saw ETA stuck at 0:00 many times and I thought there was some undocumented mechanism to "enable" the ETA calculation. 
Here, for instance, the ETA time doesn't "tick":

![Screen Shot 2019-05-21 at 17 39 30](https://user-images.githubusercontent.com/246381/58110264-80cf9a00-7bef-11e9-87ad-f1a71f714e97.png)

I have to say that sometimes the ETA ticks though, could it be a bug maybe?
The PR idea sounds interesting :)

**Comment by weavejester** [comment]
Maybe there's a rounding error or a bug with the calculation. The two functions that calculate it are:

```clojure
(defn- elapsed-time [{:keys [creation-time]}]
  (- (System/currentTimeMillis) creation-time))

(defn- remaining-time [{:keys [progress total] :as bar}]
  (let [elapsed (elapsed-time bar)]
    (if (and (pos? progress) (pos? total))
      (- (/ elapsed (/ progress total)) elapsed))))
```

**Comment by p1mps** [comment]
It was my mistake, we can close this issue. I was calculating the progress wrongly
