### ISSUE TITLE
Value out of range for int error for extremely large millisecond values

### ISSUE THREAD

**Issue by sc00terUL** [weavejester/progrock#5]
Steps to reproduce.

Run in REPL:
(interval-str 27305257000031)

This generates the error.  This progress bar is used by other projects to display a progress bar while working with files (clj-holmes).

This is tossing the "value out of range" exception and is causing my github actions to fail.

**Comment by weavejester** [comment]
For extremely large intervals, it should probably just display `--:--` rather than raising an error. PRs to fix this are welcome.

**Comment by sc00terUL** [comment]
I do have code to fix this and will be pushing a PR soon.  Trying to not just push my changes... :)  I'm new to doing an issue / fixing it / doing a PR on someone else's repo.

**Comment by sc00terUL** [comment]
PR [#6 ](https://github.com/weavejester/progrock/pull/6) fixes this issue.
